# Generated by Django 5.1.7 on 2025-03-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=5)),
            ],
        ),
    ]
