# Generated by Django 4.2.21 on 2025-05-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('course_grades', models.JSONField()),
                ('batch', models.CharField(db_index=True, default='', max_length=10)),
            ],
        ),
    ]
