# Generated by Django 5.0.7 on 2025-03-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='backlogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='Y25', max_length=4),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='registered_courses',
            field=models.IntegerField(default=0),
        ),
    ]
