# Generated by Django 5.0.7 on 2025-03-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_student_backlogs_student_batch_student_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(default='Y20', max_length=4),
        ),
    ]
