# Generated by Django 5.1.7 on 2025-03-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_student_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentY19',
            fields=[
                ('student_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('course_grades', models.JSONField()),
            ],
            options={
                'db_table': 'students_Y19',
            },
        ),
        migrations.CreateModel(
            name='StudentY20',
            fields=[
                ('student_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('course_grades', models.JSONField()),
            ],
            options={
                'db_table': 'students_Y20',
            },
        ),
    ]
