# Generated by Django 5.1.7 on 2025-03-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_studenty19_studenty20'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentY23',
            fields=[
                ('student_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('course_grades', models.JSONField()),
            ],
            options={
                'db_table': 'students_Y23',
            },
        ),
    ]
