# Generated by Django 5.0.7 on 2025-03-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_student_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='backlogs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registered_courses',
        ),
    ]
