# Generated by Django 5.0.7 on 2025-03-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_student_backlogs_remove_student_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='backlog_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='registered_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_grades',
            field=models.JSONField(default=dict),
        ),
    ]
