# Generated by Django 5.1.7 on 2025-03-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_studenty23'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentY23',
        ),
    ]
