# Generated by Django 5.1.7 on 2025-03-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_delete_studenty23'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentY19',
        ),
        migrations.DeleteModel(
            name='StudentY20',
        ),
    ]
