# Generated by Django 5.0.7 on 2025-03-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_student_backlog_count_student_batch_student_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='backlog_count',
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registered_courses',
        ),
        migrations.AlterField(
            model_name='student',
            name='course_grades',
            field=models.JSONField(),
        ),
    ]
