# Generated by Django 5.1.7 on 2025-03-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0007_delete_student_delete_studenty19_delete_studenty20'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('course_grades', models.JSONField()),
                ('batch', models.CharField(db_index=True, default='', max_length=10)),
            ],
        ),
    ]
