# Generated by Django 5.0.7 on 2025-03-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_student_batch'),
        ('adminapp', '0007_remove_student_backlog_count_remove_student_batch_and_more'),
    ]

    operations = [
    ]
